name: Update Animated Contribution SVG

on:
  schedule:
    - cron: "17 2 * * *"  # daily at 02:17 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Generate animated SVG
        env:
          GH_USERNAME: coolguy-stack
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          python scripts/animated_contrib.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add animated-contrib.svg
          git commit -m "chore: update animated contributions SVG" || echo "No changes"
          git push
